[package]
name = "tua_lexer"
version = "0.0.0"
license = "MIT"
edition = "2021"

repository = "https://github.com/tua-lua/tua/"
description = """
Tua lexer.
"""

[dependencies]

[dev-dependencies]
expect-test = "1.0"
